from typing import Tuple

from sinter import Decoder
import numpy as np

from quasicyclic.quasi_cyclic import ibm_quasi_cyclic_code_params, quasi_cyclic_from_params
from quasicyclic.bp_osd import BPOSD
import pathlib
import stim
from quasicyclic.closed_branch_decoder import CB_decoder


class sinterCBDecoder(Decoder):
    def __init__(
            self,
            max_branches: int = 25,
            max_growths: int = 5,
            max_cts: int = 3,
            max_bp_iters: int = 30,
            bp_method: str = "product_sum",
            bp_reweighting: bool = True,
            **bposd_kwargs 
    ):
        self.max_barnches = max_branches
        self.max_growths = max_growths
        self.max_cts = max_cts
        self.max_bp_iters = max_bp_iters
        self.bp_method = bp_method
        self.bp_reweighting = bp_reweighting
        self.bposd_kwargs = bposd_kwargs


    def decode_via_files(self,
                         *,
                         num_shots: int,
                         num_dets: int,
                         num_obs : int,
                         dem_path: pathlib.Path,
                         dets_b8_in_path: pathlib.Path,
                         obs_predictions_b8_out_path: pathlib.Path,
                         tmp_dir: pathlib.Path,
    ) -> None:
        """Performs decoding by reading problems from, and writing solutions to, file paths.
        Args:
            num_shots: The number of times the circuit was sampled. The number of problems
                to be solved.
            num_dets: The number of detectors in the circuit. The number of detection event
                bits in each shot.
            num_obs: The number of observables in the circuit. The number of predicted bits
                in each shot.
            dem_path: The file path where the detector error model should be read from,
                e.g. using `stim.DetectorErrorModel.from_file`. The error mechanisms
                specified by the detector error model should be used to configure the
                decoder.
            dets_b8_in_path: The file path that detection event data should be read from.
                Note that the file may be a named pipe instead of a fixed size object.
                The detection events will be in b8 format (see
                https://github.com/quantumlib/Stim/blob/main/doc/result_formats.md ). The
                number of detection events per shot is available via the `num_dets`
                argument or via the detector error model at `dem_path`.
            obs_predictions_b8_out_path: The file path that decoder predictions must be
                written to. The predictions must be written in b8 format (see
                https://github.com/quantumlib/Stim/blob/main/doc/result_formats.md ). The
                number of observables per shot is available via the `num_obs` argument or
                via the detector error model at `dem_path`.
            tmp_dir: Any temporary files generated by the decoder during its operation MUST
                be put into this directory. The reason for this requirement is because
                sinter is allowed to kill the decoding process without warning, without
                giving it time to clean up any temporary objects. All cleanup should be done
                via sinter deleting this directory after killing the decoder.
        """
        dem = stim.DetectorErrorModel.from_file(dem_path)

        myDecoder = CB_decoder(
            dem,
            max_branches = self.max_barnches,
            max_growths = self.max_growths,
            max_cts = self.max_cts,
            max_bp_iters = self.max_bp_iters,
            bp_method =  self.bp_method,
            bp_reweighting = self.bp_reweighting,
            bposd_kwargs = self.bposd_kwargs
        )

        shots = stim.read_shot_data_file(path = dets_b8_in_path,
                                         format = "b8",
                                         num_detectors = dem.num_detectors,
                                         bit_packed = False
                                        )
        predictions = myDecoder.decode_batch(shots)

        stim.write_shot_data_file(data = predictions,
                                  path = obs_predictions_b8_out_path,
                                  format = "b8",
                                  num_observables = dem.num_observables
                                  )